### ISSUE TITLE
ValueError: Layer "model_17" expects 2 input(s), but it received 1 input tensors

### ISSUE THREAD

**Issue by CatcherInThePy** [rbrtjwrk/sdgs_many_berts#1]
Hello,

First of all, thank you so much for sharing the models and the related code.

I am trying to get prediction results for a list of texts using the weights I downloaded from [Zeonodo - SDGs_many_BERTS
](https://zenodo.org/record/5918475#.ZBmXFtJByV5) but I keep getting an error from prediction functions.

I am using  Google Colab environment and I import the functions in predict.py. Then, I in a following code cell, I execute the lines starting from 150 (previously removing them from predict.py): https://github.com/rbrtjwrk/SDGs_many_BERTs/blob/0a4029324b9a8f40c06f2439e85501a0a4270a91/predict.py#L150

However, when the code tries to execute `160:predictions=models_predict(MODELS, inputs, masks)`, I get the following error:

> ValueError                                Traceback (most recent call last)
> [<ipython-input-4-7e90fc7d6fcb>](https://localhost:8080/#) in <module>
>      11 inputs=mbert.convert_to_tensor(padded_ids)
>      12 
> ---> 13 predictions=mbert.models_predict(directory='/content/drive/MyDrive/', inputs=inputs, attention_masks=masks)
>      14 
>      15 predictions_df=mbert.predictions_dict_to_df(predictions)
> 
> 3 frames
> [/content/predict.py](https://localhost:8080/#) in models_predict(directory, inputs, attention_masks, float_to_percent)
>     111     for _ in models:
>     112         model=tf.keras.models.load_model(_)
> --> 113         predictions=model.predict_step([inputs, attention_masks])
>     114         predictions=[float(_) for _ in predictions]
>     115         if float_to_percent==True:
> 
> [/usr/local/lib/python3.9/dist-packages/keras/engine/training.py](https://localhost:8080/#) in predict_step(self, data)
>    2077         """
>    2078         x, _, _ = data_adapter.unpack_x_y_sample_weight(data)
> -> 2079         return self(x, training=False)
>    2080 
>    2081     def make_predict_function(self, force=False):
> 
> [/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
>      68             # To get the full stack trace, call:
>      69             # `tf.debugging.disable_traceback_filtering()`
> ---> 70             raise e.with_traceback(filtered_tb) from None
>      71         finally:
>      72             del filtered_tb
> 
> [/usr/local/lib/python3.9/dist-packages/keras/engine/input_spec.py](https://localhost:8080/#) in assert_input_compatibility(input_spec, inputs, layer_name)
>     214 
>     215     if len(inputs) != len(input_spec):
> --> 216         raise ValueError(
>     217             f'Layer "{layer_name}" expects {len(input_spec)} input(s),'
>     218             f" but it received {len(inputs)} input tensors. "
> 
> ValueError: Layer "model_17" expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor: shape=(1, 512), dtype=int64, numpy=
> array([[  101, 10372, 10127,   143, 26728, 15634, 14059, 10114, 14084,
>         11526, 10103, 10713, 10127, 14149, 10362, 10497,   119,   102,
>             0,     0,     0,     0,     0,     0,     0,     0,     0,
>             0,     0,     0,     0,     0,     0,     0,     0,     0,
>             0,     0,     0,     0,     0,     0,     0,     0,     0,
>             0,     0,     0,     0,     0,     0,     0,     0,     0,
>             0,     0,     0,     0,     0,     0,     0,     0,     0,
>             0,     0,     0,     0,     0,     0,     0,     0,     0,
>                                         ...
>             0,     0,     0,     0]])>]
> 

The error seems to be due the line 113: https://github.com/rbrtjwrk/SDGs_many_BERTs/blob/0a4029324b9a8f40c06f2439e85501a0a4270a91/predict.py#L113

I could not fix the problem and I would be grateful if you could assist in providing a fix to the solution.

Please let me know if you need further details regarding the issue.

Thank you.

**Comment by rbrtjwrk** [comment]
Hi! I am glad you find the code and models somehow useful. Please change `model.predict_step([inputs, attention_masks])` to `model.predict([inputs, attention_masks])` and it should work. I think it may be caused by some dependencies.

**Comment by CatcherInThePy** [comment]
Hello Robert,

Wonderful! That solved the issue! Thank you so much for your quick response and for your time. I am closing the issue now.

Best regards.
